compatibility_date = "2025-10-02"
main = ".generated/workers.ts"
name = "cloesce-demo"

[[d1_databases]]
binding = "db"
database_id = "5598c78b-6fce-49de-b409-085b19fac957"
database_name = "cloesce_demo"

[vars]
